apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: jjoef9hfm-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/jjoef9hfm-dotnet-basic-gitops